build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

environment:
  matrix:
    - PRJ_GEN: "Visual Studio 14 2015 Win64"
      BDIR: msvc2015
      CFLAGS: /MD /GL

build_script:
    - mkdir build.%BDIR% && cd build.%BDIR%
    - cmake .. -G"%PRJ_GEN%"
        -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    - ctest -V --output-on-failure -C Release
