os:
- linux
- osx
dist: trusty
language: c
sudo: required
compiler:
- clang
- gcc
script:
- mkdir build
- pushd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- make
- make test
notifications:
  email:
    recipients:
    - danilo.horta@pm.me
    on_success: never
    on_failure: always
