language: c
jobs:
  include:
  - name: Build on linux-default
    os: linux
    env: GENERATOR="Unix Makefiles"
  - name: Build on linux-trusty
    os: linux
    env: GENERATOR="Unix Makefiles"
    dist: trusty
  - name: Build on osx-default
    os: osx
    env: GENERATOR="Unix Makefiles"
  - name: Build on osx-xcode6.4
    os: osx
    osx_image: xcode6.4
    env: GENERATOR="Unix Makefiles"
  - name: Build on windows
    os: windows
    env: GENERATOR="Visual Studio 15 2017 Win64"
  - name: Build on windows
    os: windows
    env: GENERATOR=Ninja
    before_install:
    - choco install ninja --no-progress -y
  - name: Install on linux-default
    os: linux
    sudo: required
    before_script: test -e /usr/bin/cmake || sudo ln -s $(which cmake) /usr/bin/cmake
    script: curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp DO_CMD=sudo bash
  - name: Install on osx-default
    os: osx
    script: curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp DO_CMD=sudo bash
  - name: Install on windows
    os: windows
    script: curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp bash
script:
- mkdir prefix
- mkdir build
- cd build
- cmake -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/prefix
  ..
- cmake --build . --config Release
- ctest --output-on-failure -C Release
- cmake --build . --config Release --target install
- test -e $TRAVIS_BUILD_DIR/prefix/include/logaddexp.h
- test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/logaddexp/logaddexp-config.cmake
- test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/logaddexp/logaddexp-targets.cmake
- cd $TRAVIS_BUILD_DIR
- git clean -xdf
notifications:
  email:
    recipients:
    - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: sAd7svBZQpvzyWFKsnWAXlG64goUIDqQ9zQASfZOBGoKkDC3ahH1Sp8WDdAAoUX4BLKiA4ia5sQuIw91cGr1XTel2CeWmd5kHBo9fdHb2Bwc/I9DvWlcMtQCm4x4E2pGS2ksQXLzLNqp5Jcw7F6cNxqwtXMNXBXEwutbbtBzMS5c732uKQSdIBWJJrQ4RvYzMVngNqHUEfhUIl8RtUv9pg2MtH0gBcpvlkmjH5g86/9KaBARh8ofjdZs+GMW3XO8fYpJKcahzGPA+ABfL7bdPUbM3khITk19sE2cie4J3qheNc2hd0xTZ3UJ7pvVBAlExa0vJdkGf+Ijc7whMXVaNohnosVVzJDcJlJ8QOZfeu8FKdSb/djOEjlRHF5ARctUVshMwnYNaEf0Fy3a6+slfH7Y9bolHnZluJIVwzgxsP0JCxonKTscOqCtdb6e5/iv6jqPkuKJsiZt8a/XDVs2q/JuLcWQ3pBtMNtsMTxoY2DESfWdAt+GnwImIn9aU71qFpYW9rrBGtSrNd36X+cE5OSf+2uRQo16XAFsfu1D/WqRdSjdDlGXZ1OR86i5BDpRlHb6YYBx50HiZ9PMU++Wh98zXNmSimNW+V6R2WcVvlxM0Ks4yM48cYjPa185sdtpl2oPTh5KwSJLyVPO5oyxbZ/NaLXPGEBfP6LDUnbrn4k=
  on:
    tags: true
    repo: horta/logaddexp
    branch: master
    skip_existing: true
