language: c
jobs:
  include:
  - os: linux
    env: GENERATOR="Unix Makefiles"
  - os: osx
    env: GENERATOR="Unix Makefiles"
  - os: windows
    env: GENERATOR="Visual Studio 15 2017 Win64"
  - os: windows
    env: GENERATOR=Ninja
    before_install:
    - choco install ninja --no-progress -y
  # - os: linux
  #   name: Install
  #   sudo: required
  #   before_script: test -e /usr/bin/cmake || sudo ln -s $(which cmake) /usr/bin/cmake
  #   script: curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp
  #     DO_CMD=sudo bash
  # - os: osx
  #   name: Install
  #   script: curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp
  #     DO_CMD=sudo bash
  # - os: windows
  #   name: Install
  #   script: curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp
  #     bash
script:
- mkdir prefix
- mkdir build
- cd build
- cmake -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/prefix
  ..
- cmake --build . --config Release
- ctest --output-on-failure -C Release
- cmake --build . --config Release --target install
- test -e $TRAVIS_BUILD_DIR/prefix/include/logaddexp.h
- test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/logaddexp/logaddexp-config.cmake
- cd $TRAVIS_BUILD_DIR
- git clean -xdf
notifications:
  email:
    recipients:
    - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: Ks7CDIPJw+s1/lPO02hrUxuWuhLqe4DE/JMd0/Hwi4ZBqBzfLhetIiVIyL+s/kVEGSJaaRgYHDUy/Du6w8RHyizO4tyJGdGqZakLd0C7ukqk59v6oFphll+9ZfM5TLMuXOtFEVFQvojgaKEIZBvl7IVn1pMebkv/5twf2wx6MMA0TiYLe52ZaP6L1ltJtK9LHcRajwenjVlRhq3IZHR7cLqX5SWoYtIucRupRMc+EsZbQH0JxtQvbLqPt6pqMRM0JWNQhmCnp+8X57D7wbpChOHjSp8dVXP0bSMKesAYrSIf8yQyjdolccDTMFbGrhIl26QZGPsIcwm3mR33vPQTMVfGDXqwnqeTsKMBDo8uSonj1u8FxanGVX4JrUMOY3GPOl3sAwqayBWxi1GUo8/JsfxLzfMr8s7AhcUYzQ69iKRzbJBsRj38xiAdd0sv/DLIZ4AvybMGbLecBVW31UTnDmuBLBj/tUTILBCtG7yEAqXalRq0qgmJjLavgYQ6EIdzZnQv5HitHEkp67nPRkM7cG344DmBkGk8X8WGe8Zzm7Xs7zBAlIk1KxEnQ7B0wR00MejQPfX7KPLxjYXCUbXJrVFcHu+OoWjRuhr3FlF6WavbzW1+zHC4a40I39kMcuWz6sF4O9/Rm9nmO/APNUsjHwwNZT86xJOog+MlYboRtn4=
  on:
    tags: true
    repo: horta/logaddexp
    branch: master
    skip_existing: true
