os:
- linux
- osx
language: c
compiler:
- clang
- gcc
script:
- mkdir build
- cd build
- cmake ..
- cmake --build .
- cmake --build . --target test
notifications:
  email:
    recipients:
    - danilo.horta@pm.me
    on_success: never
    on_failure: always
