language: c
jobs:
  include:
  - os: linux
    env: GENERATOR="Unix Makefiles"
  - os: osx
    env: GENERATOR="Unix Makefiles"
  - os: windows
    env: GENERATOR="Visual Studio 15 2017 Win64"
  - os: windows
    env: GENERATOR=Ninja
    before_install:
    - choco install ninja --no-progress -y
script:
- mkdir prefix
- mkdir build
- cd build
- cmake -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/prefix
  ..
- cmake --build . --config Release
- ctest --output-on-failure -C Release
- cmake --build . --config Release --target install
- test -e $TRAVIS_BUILD_DIR/prefix/include/logaddexp.h
- test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/logaddexp/logaddexp-config.cmake
- cd $TRAVIS_BUILD_DIR
- git clean -xdf
notifications:
  email:
    recipients:
    - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: l64/AUBDPJz9MB5m0fJhOOjorwV2NC6Oh4c/CQdMeY+Ur6/BBsU4M0SXk1zWa/+jGO5dTzYlKcgLg4nr7AYQ4KBpfs+X09+hMjhxyyLr4iWyybPKCCLBaVwIlsvoiWXJz6p8Hyw6q4dkAz3b0cFeFAzusJZVwSYxMg/mjItewc2FcHuy66L5PyfEkzecb2j+zvdBxxDbSofwxeNifziVql3faIFuei9n/eUows+MGEWRxqhImzGsnlB13aDwVlzNnk0w4OD1CHckAbrbOfonHgcxT2+Vhc7r1J/2HM41AiYAR8vk70QtjIWMDb5jdz0VFykFnMabY1Vp7CUInyijQMabPfSRCJIfyV/gXkQas+EXqM9W7n95/gaDFlonXbrYZcNGVv/VMgx1zgue8BajIp3Shfm++uExlZ2rtag1lGcxfLR/Q9+ScQJFNsSthyrn9N+6hPYMWDk7CjgE9JwMEZzLFt5MjZPSUsav4hUAhGP03WkzQdIJa2Kii2us5iiBDLvU65hB7CkxcIqWmdk43RATxwBD3usR2yLVNBwL8KdbVpABx6reUrh1p5FxxzORnJkqsgEJrISCBgZf/HW/Jo5fCdaA6wTKlQUC7tKNDHn9dP4uS7jZ/gR3mYvoQt9GsdRTt0cx/Kvcw03Jf14IsdkMTc3oI8QnsugDFqyNqhs=
  on:
    tags: true
    repo: horta/logaddexp
    branch: master
    skip_existing: true
